Change cosoms sample from track1 to track2(Azure CosmosDB sample forhigh availability)
Azure-Samples/cosmosdb-java-create-documentdb-and-configure-for-eventual-consistency pull request #1
Opened 2020-05-12 09:11 UTC by Melanie-Ma

Change cosoms sample from track1 to track2(Azure CosmosDB sample for high availability)

2020-05-12 09:11 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure-Samples/cosmosdb-java-create-documentdb-and-configure-for-eventual-consistency?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure-Samples/cosmosdb-java-create-documentdb-and-configure-for-eventual-consistency?pullRequest=1) before we can accept your contribution.<br/><br/>:x: Melanie-Ma [sign now](https://cla.opensource.microsoft.com/Azure-Samples/cosmosdb-java-create-documentdb-and-configure-for-eventual-consistency?pullRequest=1)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure-Samples/cosmosdb-java-create-documentdb-and-configure-for-eventual-consistency?pullRequest=1) it.</sub>

2020-07-27 18:47 UTC, jongio requested changes

2020-07-27 18:47 UTC, jongio commented on pom.xml
> +      <version>4.0.0-preview.1</version>
Update to GA

2020-07-27 18:47 UTC, jongio commented on src/main/java/com/microsoft/azure/management/cosmosdb/samples/CreateCosmosDBWithEventualConsistency.java
> +            CosmosClient cosmosClient=CosmosClient.builder()
Spacing

2020-07-28 09:32 UTC, Melanie-Ma commented on pom.xml
> +      <version>4.0.0-preview.1</version>
I have updated to GA

2020-08-08 12:23 UTC, jongio commented
@anuchandy - Please review. Thanks, Jon

2020-08-19 16:43 UTC, anuchandy commented
@kushagraThapar - could you help review this?

2020-08-19 17:17 UTC, kushagraThapar requested changes

2020-08-19 17:17 UTC, kushagraThapar commented on src/main/java/com/microsoft/azure/management/cosmosdb/samples/CreateCosmosDBWithEventualConsistency.java
> +            ThroughputProperties properties = ThroughputProperties.createAutoscaledThroughput(throughput);
Just a heads up, you are using autoscaling feature of Cosmos here. Is this intentional?

2020-08-19 17:17 UTC, kushagraThapar commented on src/main/java/com/microsoft/azure/management/cosmosdb/samples/CreateCosmosDBWithEventualConsistency.java
> +    private static void createDBAndAddCollection(String masterKey, String endPoint) throws CosmosException {
We have rebranded Cosmos names. Like `Collection` to `Container` - please change it here.

2020-08-19 17:17 UTC, anuchandy commented on src/main/java/com/microsoft/azure/management/cosmosdb/samples/CreateCosmosDBWithEventualConsistency.java
> +            CosmosContainerProperties containerProperties = new CosmosContainerProperties(COLLECTION_ID,"/id");
nit; add a space after `,`.

2020-08-19 17:17 UTC, anuchandy commented on src/main/java/com/microsoft/azure/management/cosmosdb/samples/CreateCosmosDBWithEventualConsistency.java
> +            System.out.println(cosmosDatabase.toString());
I could not find a `toString` method in `CosmosDatabase` type, so not sure this will print any useful info other than the class name.

2020-08-24 08:44 UTC, Melanie-Ma commented
@anuchandy-  Please review, thanks.

2020-08-24 21:49 UTC, anuchandy approved these changes

2020-09-09 15:36 UTC, conniey approved these changes

2020-09-09 15:36 UTC, conniey commented on src/main/java/com/microsoft/azure/management/cosmosdb/samples/CreateCosmosDBWithEventualConsistency.java
> +                .consistencyLevel(ConsistencyLevel.SESSION).buildClient();
nit: .buildClient()
on a new line

2020-09-09 15:36 UTC, conniey commented on pom.xml
> +      <version>4.2.0</version>
I believe 4.3.1 is the latest
https://search.maven.org/artifact/com.azure/azure-cosmos/4.3.1/jar

2020-09-15 18:49 UTC, conniey approved these changes

2020-09-15 18:49 UTC, conniey commented on pom.xml
> +      <version>4.4.0-beta.1</version>
Should be pointing to a GA version rather than a beta one.

2020-10-19 19:13 UTC, merged